substitutions:
  _AR_REGION: asia-south1
  _RUN_REGION: us-central1
  _SERVICE: vajrixai-web

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/vajrixai-web/${_SERVICE}:$BUILD_ID
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/vajrixai-web/${_SERVICE}:$BUILD_ID

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/vajrixai-web/${_SERVICE}:$BUILD_ID
      - --region
      - ${_RUN_REGION}
      - --platform
      - managed
      - --no-invoker-iam-check
      - --port
      - "8080"
      - --max-instances
      - "3"

images:
  - ${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/vajrixai-web/${_SERVICE}:$BUILD_ID
